### ISSUE TITLE
People are confused by chat messages, they don't know which plugin it's coming from.

### ISSUE THREAD

**Issue by geheur** [Kraelll/ClassesOfGielinor#3]
Multiple people have asked in runelite support channel where the "<col=ff9040>Protect from Melee!</col>clicked" message comes from.
Could it be made to be more clear what plugin it comes from? e.g. add "your class cannot use that!" maybe?

**Comment by Kraelll** [comment]
Hi there

Unfortunately this is a bit of debugging code I (foolishly) left behind. It's been commented out in the latest release, which I will commit/release ASAP. 🙂
